name: "Bug Report"
description: "Report a problem with the RT Model Card Writing Tool"
title: "[Bug]: "
labels: ["bug"]

body:
  - type: textarea
    id: describe
    attributes:
      label: "Describe the Bug"
      description: "A clear and concise description of what the bug is."
    validations:
      required: true

  - type: checkboxes
    id: location
    attributes:
      label: "Where is the bug?"
      options:
        - label: "Website (Streamlit app)"
        - label: "Repository content (e.g., documentation, data)"

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "Please describe the steps to reproduce the issue."
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen?"

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem."

  - type: input
    id: environment
    attributes:
      label: "Environment"
      description: |
        Device, OS, Browser, Repository version/branch.
      placeholder: |
        Device: PC
        OS: Ubuntu 22.04
        Browser: Chrome 124
        Repo: main

  - type: textarea
    id: context
    attributes:
      label: "Additional Context"
      description: "Add any other context about the problem here."

  - type: checkboxes
    id: security
    attributes:
      label: "Is this a security vulnerability?"
      description: "If yes, please report confidentially as per SECURITY.md."
      options:
        - label: "Yes"
        - label: "No"
