name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system packages (PDF stack)
        run: |
          sudo apt-get update
          xargs -a .github/system-deps.txt sudo apt-get install -y

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install package (dev extras)
        run: pip install -e ".[dev]"

      - name: Lint with Ruff
        run: ruff check .

      - name: Type-check with mypy
        run: mypy .

      - name: Run tests
        run: pytest -q
