name: Ruff on Changed Files
on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.py

      - name: Run Ruff on changed files
        if: steps.changed-files.outputs.all_changed_files != ''
        uses: astral-sh/ruff-action@v2
        with:
          src: ${{ steps.changed-files.outputs.all_changed_files }}

